spring.application.name=ezz

spring.datasource.url=jdbc:mysql://mysql-3ad7b097-mindmaster3-0183.i.aivencloud.com:12584/defaultdb?ssl-mode=REQUIRED&useSSL=true
spring.datasource.username=avnadmin
# please don't fuck up my database
spring.datasource.password=AVNS_V5V4MMJToZ7OY5UKcPN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# when attempting to delete all the data
#spring.jpa.hibernate.ddl-auto=create
# temporary false to make it a little faster
spring.jpa.show-sql=false


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port (optional)
server.port=8080

# to make sure the could connection is stable
# only 2 maximum pools temp for ezz
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=30000